<!DOCTYPE html>
<html lang="es">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1.0"/>
    <title>Reservaciones</title>
    <link rel="stylesheet" href="<?php echo $this->url->get('css/materialize.css')?>"/>
    <link rel="stylesheet" href="<?php echo $this->url->get('css/dataTables.bootstrap.min.css')?>"/>
    <link rel="stylesheet" href="<?php echo $this->url->get('css/style.css')?>"/>
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/icon.png')?>"/>
    <script src="<?php echo $this->url->get('js/jquery.js')?>"></script>
  </head>
  <body class="grey lighten-2">
      <?php echo $this->getContent(); ?>
    </div>
    <script src="<?php echo $this->url->get('js/materialize.js')?>"></script>
    <script src="<?php echo $this->url->get('js/datatables.js')?>"></script>
    <script src="<?php echo $this->url->get('js/dataTables.bootstrap.min.js')?>"></script>
    <script src="<?php echo $this->url->get('js/init.js')?>"></script>
    <script src="<?php echo $this->url->get('js/funciones.js')?>"></script>
  </body>
</html>
