<?php
$reservar = '';
$restaurante = '';

if($this->session->get("privilegios") != 0)
{
  $reservar = "<a href='reservar'>Reservar</a>";
  $restaurante = "<a href='restaurante'>Restaurante</a>";
}
?>
<nav class="blue-grey darken-3" role="navigation">
  <ul class="right hide-on-med-and-down">
    <li><a href="index/logout">Salir</a></li>
  </ul>
  <ul class="right hide-on-med-and-down">
    <li><a href="usuarios">Usuario</a></li>
  </ul>
  <ul class="right hide-on-med-and-down">
    <li><?php echo $restaurante; ?></li>
  </ul>
  <ul class="right hide-on-med-and-down">
    <li><a href="reportes">Reportes</a></li>
  </ul>
  <ul class="right hide-on-med-and-down">
    <li><a href="busqueda">Buscar</a></li>
  </ul>
  <ul class="right hide-on-med-and-down">
    <li><?php echo $reservar; ?></li>
  </ul>
  <ul id="nav-mobile" class="sidenav">
    <li><?php echo $reservar; ?></li>
    <li><a href="busqueda">Buscar</a></li>
    <li><a href="reportes">Reportes</a></li>
    <li><?php echo $restaurante; ?></li>
    <li><a href="usuarios">Usuario</a></li>
    <li><a href="index/logout">Salir</a></li>
  </ul>
  <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
</nav>
<div class="container">
<br>
<?php echo $this->getContent(); ?>